merge feat/weight-edit
Elianpullen/AEfitness pull request #3
Opened 2024-04-25 13:43 UTC by Elianpullen

- added weight edit, delete feat
- improved weight feat
- changed MVC names
- moved empty state handling to view
- refactored code comments
- changed date format
- refactored app.js
- added nav weight dropdown

2024-04-25 21:10 UTC, Gigabyte0x1337 requested changes
Algemeen prima wat kleine puntjes je moet zelf maar kijken of je belangrijk vind

2024-04-25 21:10 UTC, Gigabyte0x1337 commented on resources/views/weight/graph.blade.php
> +        $weightDate = [];
$weightDates misschien betere naam nu kan je ze makkelijk door elkaar halen met $weightData

2024-04-25 21:10 UTC, Gigabyte0x1337 commented on app/Http/Controllers/WeightDataController.php
> +     * Display a listing of the resource.
Comments boven methodes zijn heel generiek, misschien resource is een beetje te algemeen geld voor alle comments

2024-04-25 21:10 UTC, Gigabyte0x1337 commented on resources/js/app.js
>      options: {},
Is options: {}, echt nodig kan je die niet weg laten

2024-04-26 09:21 UTC, Elianpullen commented on resources/views/weight/edit.blade.php
> +                                    id="date" name="date" type="date" value="{{$weight->date}}">
Ik zie alleen maar {{$value}} in mijn code voorkomen ;)

2024-04-26 09:25 UTC, Gigabyte0x1337 commented on resources/views/weight/edit.blade.php
> +                                    id="date" name="date" type="date" value="{{$weight->date}}">
{{ Auth::user()->name }} bijv. dat bedoelde ik

2024-04-26 09:35 UTC, Elianpullen commented on resources/views/weight/edit.blade.php
> +                                    id="date" name="date" type="date" value="{{$weight->date}}">
Ja, dat klopt inderdaad.
Dat is automatisch gegenereerde code met de installatie van Jetstream.

2024-04-26 09:44 UTC, Gigabyte0x1337 approved these changes

2024-04-26 09:44 UTC, merged